### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by hein4105** [nilsTI/Dabbsson_control#1]
Ich habe am Wochenende angefangen und iobroker den API-Zugriff mit Javascript umgesetzt und versuche das erst einmal ohne produktive Daten umzusetzen. Ich habe mir zusätzlich noch einen Raspberry Zero bestellt und werde dann am nächsten Wochenende dann diesen bestücken und lauffähig machen.

{'protocol': 4, 't': 63848, 'data': {'dps': {'1': 9, '2': 4761, '10': 19, '103': 0, '104': 0, '105': 0, '106': 0, '110': 0, '108': 0, '138': 25, '139': 0}}, 'dps': {'1': 9, '2': 4761, '10': 19, '103': 0, '104': 0, '105': 0, '106': 0, '110': 0, '108': 0, '138': 25, '139': 0}}

1 | State of charge DBS2300 in %
2???
10 | Temperature of DBS2300
103 | DC-Input of DBS2300
104????
105 | DC-Output of DBS3000B
106 ????
108 | Output of DBS2300
109 | AC-Out on/off
110????
111 | 5V-Out on/off
112 | 12V-Out on/off
123 | A/C input power
138 | State of charge DBS3000B in %
139????
156 | Base64 encoded information of DBS3000B (including keys 205, 206, 208, 209, 220, 221, 222)

Ich habe vor, die Eingangsleistung in Watt dynamisch zu steuern und zwar auf Basis der aktuell vorhandenen Kapazitäten und die Ausgangsleistung in Watt.

Das fehlt mir bisher. und kann die Beladung und die Einspeisung bisher per schaltbarer Steckdose steuern.
Das reicht mir aber nicht, weil ich bisher die Eingangsleistung in Watt vorgeben muss in der App.

**Comment by nilsTI** [comment]
Das sind noch nicht alle key-value-Paare. Wenn du dich mit der offiziellen Tuya-App verbindest, wirst du noch mehr sehen/herausfinden.
![Untitled](https://github.com/nilsTI/Dabbsson_control/assets/62245241/ecdac394-d881-49eb-a776-f5a8cf716811)

Da einige Bezeichnungen nur Schriftzeichen sind, müsstest du etwas rumprobieren.

Willst du die A/C-Eingangsleistung dynamisch steuern? -> z.B. mit send_payload(d, {'123': 600})
"vorhandenen Kapazitäten" -> im Feld 1
"Ausgangsleistung in Watt" -> im Feld 108

Ist das nicht schon alles, was du brauchst?
Ansonsten empfehle ich Dir wirklich mit der Tuya-App rumzuspielen. 
Du siehst dann auch direkt, was gesendet und empfangen wird.

**Comment by IngAley** [comment]
Hallo Kollegen,
ich bin dabei eine 'Nulleinspeisung' mit Dabbsson DBS2300 und DBS600M über iobroker zu realisieren.
Hab die Dabbsson Geräte über den Tuya-Adapter in den Iobroker eingebunden - da siehst du dann alle Werte direkt in den Datenpunkten, und kannst über diese die gewünschten Werte lesen und schreiben...
Die Werte der DBS2300 werden alle 5 Sekunden aktualisiert. Die vom Inverter leider nur alle 60 Sekunden. Diesbezüglich bin ich noch am Tüfteln.
Aber sonst geht das relativ einfach...

**Comment by hein4105** [comment]
Guten Morgen, ich bin auch dabei mit iobroker und javascript das anzubinden. wie hast du das in iobroker gemacht?

**Comment by IngAley** [comment]
1. "Tuya Smart Life" App am Smartphone installieren und registrieren 
2. Dabbsson Geräte in die "Tuya Smart Life" App einbinden, IOT-Reset drücken, und Geräte suchen (dann sind sie aus der Dabbsson App raus)
3. Tuya-Adapter in iobroker installieren und konfigurieren 
4. Geräte einmal aus der Cloud einlesen, danach werden sie vom Adapter lokal ausgelesen (ist gut beschrieben)
5. Alle Datenpunkte werden automatisch angelegt
6. Die Werte aus den Datenpunkten in Scripten weiterverarbeiten und auch schreiben ;-)

**Comment by IngAley** [comment]
Hier Topic im iobroker forum:
[https://forum.iobroker.net/topic/74100/dabbsson-dbs2300-dbs600m-mit-iobroker-steuern](url)

....da können wir die iobroker Details diskutieren :-)

**Comment by hein4105** [comment]
ok, das bedeutet, wenn ich die Datenpunkte in iobroker vetändere, dann wird das automatisch zur batterie gepushed. Mit Javascript sollte das kein Problem darstellen.

**Comment by hein4105** [comment]
Funktioniert jetzt fehlerfrei, vielen Dank für euren Erkenntnisse.
